<?php

/**
 * This file is part of the package T3Planet/rte-ckeditor-pack.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

namespace T3Planet\RteCkeditorPack\DataProvider\Cards;

use TYPO3\CMS\Extbase\Utility\LocalizationUtility;

class CardData
{
    protected string $localLanguage;

    protected string $btnTitle;

    protected array $modules;

    public function __construct()
    {
        // Initialize the local language
        $this->localLanguage = 'LLL:EXT:rte_ckeditor_pack/Resources/Private/Language/locallang.xlf:';

        $this->btnTitle =  LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack');

        $this->modules = [
            'TrackChanges' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.track_changes', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.track_changes', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.track_changes.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-document-edit',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html',
            ],
            'Comments' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.comments', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.comments', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.comments.description', 'rte_ckeditor_pack'),
                'icon' => 'content-messages',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments.html',
            ],
            'ImportWord' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.import_from_word', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.import_from_word', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.import_from_word.description', 'rte_ckeditor_pack'),
                'icon' => 'mimetypes-word',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/converters/import-word/import-word.html',
            ],
            'RevisionHistory' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.revision_history', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.revision_history', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.revision_history.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-history',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/revision-history/revision-history.html',
            ],
            'ExportPdf' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_pdf', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_pdf', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_pdf.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-file-pdf',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'large',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/converters/export-pdf.html',
            ],
            'ExportWord' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_word', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_word', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.export_to_word.description', 'rte_ckeditor_pack'),
                'icon' => 'mimetypes-word',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'large',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/converters/export-word.html',
            ],
            'ToggleAi' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.toggle_ai', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.toggle_ai', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.toggle_ai.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_toggleAi',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/ai/ckeditor-ai-overview.html',
            ],
            'Footnotes' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.footnotes', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.footnotes', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.footnotes.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_footnotes',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/footnotes.html',
            ],
            'WProofreader' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.spell_and_grammar_check', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.spell_and_grammar_check', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.spell_and_grammar_check.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-check-badge-alt',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/spelling-and-grammar-checking.html#wproofreader-cloud',
            ],
            'Pagination' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.pagination', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.pagination', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.pagination.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-pagetree',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination.html',
            ],
            'MultiLevelList' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.multi_level_list', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.multi_level_list', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.multi_level_list.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_multiLevelList',
                'modalSize' => 'small',
                'buttonTitle' => $this->btnTitle,
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/lists/multi-level-lists.html#common-api',
            ],
            'Mention' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.mention', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.mention', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.mention.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-pagetree',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html',
            ],
            'RealTimeCollaboration' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.real_time_collaboration', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.real_time_collaboration', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.premium.real_time_collaboration.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-list',
                'data_confirmation' => 'false',
                'buttonTitle' => $this->btnTitle,
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration.html',
            ],
            'SlashCommand' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.slash_commands', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.slash_commands', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.slash_commands.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-link',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'large',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/slash-commands.html',
            ],
            'Template' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.templates', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.templates', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.templates.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-viewmode-tiles',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'large',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/template.html',
            ],
            'PasteFromOfficeEnhanced' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.paste_from_office_enhanced', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.paste_from_office_enhanced', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.paste_from_office_enhanced.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-file-openoffice',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.checkbox.enable', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html',
            ],
            'FormatPainter' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.format_painter', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.format_painter', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.format_painter.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-brush',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.checkbox.enable', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/format-painter.html',
            ],
            'DocumentOutline' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.document_outline', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.document_outline', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.document_outline.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-document-view',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/document-outline.html',
            ],
            'FullScreen' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.full_screen_mode', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.full_screen_mode', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.full_screen_mode.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-fullscreen',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/fullscreen.html',
            ],
            'MergeFields' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.merge_fields', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.merge_fields', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.merge_fields.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-variable-add',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'large',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/merge-fields.html',
            ],
            'TableOfContents' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.table_contents', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.table_contents', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.table_contents.description', 'rte_ckeditor_pack'),
                'icon' => 'content-menu-pages',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.checkbox.enable', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/table-of-contents.html',
            ],
            'CaseChange' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.case_change', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.case_change', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.productivity.case_change.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_caseChange',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/case-change.html',
            ],
            'Images' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.images', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.images', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.images.description', 'rte_ckeditor_pack'),
                'icon' => 'content-image',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://docs.typo3.org/p/t3planet/rte-ckeditor-pack/main/en-us/Features/Media&VisualContent/Index.html',
            ],
            'Indentation' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.block_indentation', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.block_indentation', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.block_indentation.description', 'rte_ckeditor_pack'),
                'icon' => 'content-beside-text-img-above-center',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/indent.html',
            ],
            'Bookmark' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.bookmark', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.bookmark', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.bookmark.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_bookmark',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/bookmarks.html',
            ],
            'Font' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.fonts', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.fonts', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.fonts.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-file-text',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/font.html',
            ],
            'HighLight' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.highlight', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.highlight', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.highlight.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-open',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html',
            ],
            'Heading' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.heading', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.heading', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.heading.description', 'rte_ckeditor_pack'),
                'icon' => 'content-header',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/headings.html',
            ],
            'Alignment' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.alignment', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.alignment', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.alignment.description', 'rte_ckeditor_pack'),
                'icon' => 'content-beside-text-img-above-center',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html',
            ],
            'Style' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.style', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.style', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.style.description', 'rte_ckeditor_pack'),
                'icon' => 'content-beside-text-img-above-center',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/style.html',
            ],
            'PageBreak' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.page_break', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.page_break', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.page_break.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-insert',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html',
            ],
            'TextTransformation' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.text_transformation', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.text_transformation', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.text_transformation.description', 'rte_ckeditor_pack'),
                'icon' => 'form-text',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/text-transformation.html',
            ],
            'ListProperties' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.document_list', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.document_list', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.document_list.description', 'rte_ckeditor_pack'),
                'icon' => 'apps-clipboard-list',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists-properties.html',
            ],
            'WordCount' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.word_count', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.word_count', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.word_count.description', 'rte_ckeditor_pack'),
                'icon' => 'content-widget-number',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html',
            ],
            'HtmlEmbed' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.htmlEmbed', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.htmlEmbed', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.htmlEmbed.description', 'rte_ckeditor_pack'),
                'icon' => 'content-carousel-html',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/html/html-embed.html',
            ],
            'Code' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.code', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.code', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.code.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-code',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html',
            ],
            'CodeBlock' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.codeBlock', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.codeBlock', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.codeBlock.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-file-html',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html',
            ],
            'BlockToolbar' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.blockToolbar', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.blockToolbar', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.blockToolbar.description', 'rte_ckeditor_pack'),
                'icon' => 'apps-toolbar-menu-actions',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/editor-types.html#balloon-editor-and-balloon-block-editor',
            ],
            'BalloonToolbar' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.balloonToolbar', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.balloonToolbar', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.balloonToolbar.description', 'rte_ckeditor_pack'),
                'icon' => 'apps-toolbar-menu-workspace',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/editor-types.html#balloon-editor-and-balloon-block-editor',
            ],
            'Markdown' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.markdown', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.markdown', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.markdown.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-barcode-read',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html',
            ],
            'MediaEmbed' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.mediaEmbed', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.mediaEmbed', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.mediaEmbed.description', 'rte_ckeditor_pack'),
                'icon' => 'content-textmedia',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html',
            ],
            'ShowBlocks' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.showBlocks', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.showBlocks', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.showBlocks.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-extension',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/show-blocks.html',
            ],
            'TextPartLanguage' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.textPartLanguage', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.textPartLanguage', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.textPartLanguage.description', 'rte_ckeditor_pack'),
                'icon' => 'install-manage-language',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/language.html',
            ],
            'Menubar' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.menuBar', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.menuBar', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.menuBar.description', 'rte_ckeditor_pack'),
                'icon' => 'content-menu-related',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/menubar.html',
            ],
            'Emoji' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.emoji', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.emoji', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.emoji.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_emoji',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'small',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/emoji.html',
            ],
            'LineHeight' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.lineHeight', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.lineHeight', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.lineHeight.description', 'rte_ckeditor_pack'),
                'icon' => 'actions-chevron-expand',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/line-height.html',
            ],
            'SourceEditingEnhanced' => [
                'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.sourceEditingEnhanced', 'rte_ckeditor_pack'),
                'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.sourceEditingEnhanced', 'rte_ckeditor_pack'),
                'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.sourceEditingEnhanced.description', 'rte_ckeditor_pack'),
                'icon' => 'rte_sourceEditingEnhanced',
                'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
                'modalSize' => 'medium',
                'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/source-editing/source-editing-enhanced.html',
            ],
            // 'Typo3Image' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.file_management.typo3Image', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.file_management.typo3Image', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.file_management.typo3Image.description', 'rte_ckeditor_pack'),
            //     'icon' => 'content-image',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.checkbox.enable', 'rte_ckeditor_pack'),
            //     'modalSize' => 'medium',
            //     'docs' => 'https://docs.typo3.org/p/t3planet/rte-ckeditor-pack/main/en-us/Features/Media&VisualContent/Index.html',
            // ],
            // 'Image' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.auto_image', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.auto_image', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.ckeditor5Plugins.auto_image.description', 'rte_ckeditor_pack'),
            //     'icon' => 'content-image',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage . 'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            //     'modalSize' => 'medium',
            //     'docs' => 'https://ckeditor.com/docs/ckeditor5/latest/features/image.html',
            // ],
            // 'MathEquations' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.math_equations', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.math_equations', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.math_equations.description', 'rte_ckeditor_pack'),
            //     'icon' => 'apps-toolbar-menu-systeminformation',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'coming_soon' => true,
            //     'modalSize' => 'small',
            // ],
            // 'CkBox' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.file_management.ckbox', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.file_management.ckbox', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.file_management.ckbox.description', 'rte_ckeditor_pack'),
            //     'icon' => 'form-image-upload',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'coming_soon' => true,
            //     'modalSize' => 'small',
            // ],
            // 'FindAndReplace' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.find_and_replace', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.find_and_replace', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.find_and_replace.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-replace',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            // ],
            // 'Notification' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.notifications', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.notifications', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.premium.notifications.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-list',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'coming_soon' => true,
            //     'modalSize' => 'small',
            // ],
            // 'TextStyles' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.text_style', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.text_style', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.text_style.description', 'rte_ckeditor_pack'),
            //     'icon' => 'content-header',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            //     'modalSize' => 'medium',
            // ],
            // 'SelectAll' =>[
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.select_all', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.select_all', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.select_all.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-selection-elements-all',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            // ],
            // 'SpecialCharacters' =>[
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.special_characters', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.special_characters', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.special_characters.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-heart',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            // ],
            // 'Autosave' =>[
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.autosave', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.autosave', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.autosave.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-save-add',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            //     'modalSize' => 'medium',
            // ],
            // 'SourceEditing' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.sourceEditing', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.sourceEditing', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.sourceEditing.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-file-edit',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            //     'modalSize' => 'medium',
            // ],
            // 'CollaborativeDocumentEditor' =>  [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeDocumentEditor', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeDocumentEditor', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeDocumentEditor.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-chat',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'modalSize' => 'small',
            //     'coming_soon' => true
            // ],
            // 'FeatureRichEditor' =>  [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.FeatureRichEditor', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.FeatureRichEditor', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.FeatureRichEditor.description', 'rte_ckeditor_pack'),
            //     'icon' => 'module-rte-ckeditor',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'modalSize' => 'small',
            //     'coming_soon' => true,
            // ],
            // 'DocumentEditor' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.DocumentEditor', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.DocumentEditor', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.DocumentEditor.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-document-synchronize',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'modalSize' => 'small',
            //     'coming_soon' => true
            // ],
            // 'CollaborativeArticleEditor' => [
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeArticleEditor', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeArticleEditor', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.layout.CollaborativeArticleEditor.description', 'rte_ckeditor_pack'),
            //     'icon' => 'actions-document-edit',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.coming-soon', 'rte_ckeditor_pack'),
            //     'modalSize' => 'small',
            //     'coming_soon' => true
            // ],
            // 'RestrictedEditingMode' =>[
            //     'title' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.restrictedEditing', 'rte_ckeditor_pack'),
            //     'subtitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.restrictedEditing', 'rte_ckeditor_pack'),
            //     'description' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.ckeditor5Plugins.restrictedEditing.description', 'rte_ckeditor_pack'),
            //     'icon' => 'overlay-restricted',
            //     'buttonTitle' => LocalizationUtility::translate($this->localLanguage.'ckeditorKit.tab.card.btn_title', 'rte_ckeditor_pack'),
            //     'modalSize' => 'small',
            //     'coming_soon' => true,
            // ],

        ];

    }

    public function getDetailsByKey(string $key): ?array
    {
        return $this->modules[$key] ?? null;
    }

    public function getIconByKey(string $key): string
    {
        if (array_key_exists($key, $this->modules)) {
            return $this->modules[$key] ? $this->modules[$key]['icon'] : '';
        }
        return '';
    }
}
